feat(absinthe): add relay connection
Byzanteam/jet-ext pull request #14
Opened 2022-12-27 09:33 UTC by vanppo

2022-12-27 09:43 UTC, fahchen requested changes
测试得搞一下哇

2022-12-27 09:48 UTC, fahchen commented on lib/jet_ext/absinthe/relay/connection/cursor.ex
> +      |> Base.decode64!(padding: false)
```suggestion
      |> Base.url_decode64!(padding: false)
```

2022-12-27 09:48 UTC, fahchen commented on lib/jet_ext/absinthe/relay/connection/cursor.ex
> +      |> :erlang.binary_to_term()
防止攻击
```suggestion
      |> :erlang.binary_to_term([:safe])
```

2022-12-27 09:48 UTC, fahchen commented on lib/jet_ext/absinthe/relay/connection/cursor.ex
> +    |> Base.encode64(padding: false)
```suggestion
    |> Base.url_encode64(padding: false)
```

2022-12-28 02:51 UTC, fahchen requested changes

2022-12-28 02:51 UTC, fahchen commented on lib/jet_ext/absinthe/relay/connection.ex
> +          include_tail_edge: Keyword.get(opts, :include_tail_edge) || false
@CptBreeza @moonRider @vanppo 我们当时为啥要设计这两个参数进去啊？

2022-12-28 02:51 UTC, fahchen commented on test/jet_ext/absinthe/relay/connection/query_test.exs
> +end
这里要测试一下 where 是否是符合要求

2022-12-28 03:35 UTC, fahchen approved these changes

2022-12-28 05:27 UTC, CptBreeza commented on lib/jet_ext/absinthe/relay/connection.ex
> +          include_tail_edge: Keyword.get(opts, :include_tail_edge) || false
记得不太清楚了，好像是做 websocket 推送更新的时候，不支持这两个参数会导致一些困难？

2022-12-28 05:28 UTC, CptBreeza approved these changes

2022-12-28 06:02 UTC, merged