Implement asbinthe object json scalar type
Byzanteam/jet-ext pull request #30
Opened 2023-12-14 07:25 UTC by c01dcat

- [x] implement Absinthe `ObjectJSON` scalar type to represents arbitrary JSON string data, represented as UTF-8
      character sequences

2023-12-14 07:33 UTC, CptBreeza commented on lib/jet_ext/absinthe/types/scalar/object_json.ex
> +    defp iterate(value), do: value
这个应该有点不对，因为这个类型咱们只允许它最外层是一个 object，现在这样的写法会允许外层是任意类型。
这样改一下：把这些 `iterate` 改名成 `do_iterate`，然后再写一个 `iterate` 函数，它首先检查 value 是不是 map（而且需要排除 struct），不是的话报错，是的话再去调 do_iterate

2023-12-14 07:36 UTC, fahchen requested changes

2023-12-14 07:36 UTC, fahchen commented on lib/jet_ext/absinthe/types/scalar/object_json.ex
> +if Code.ensure_loaded?(Absinthe) do
```suggestion
if Code.ensure_loaded?(Absinthe) && Code.ensure_loaded?(Jason) do
```

2023-12-14 07:36 UTC, fahchen commented on lib/jet_ext/absinthe/types/scalar/object_json.ex
> +      The `ObjectJSON` scalar type represents arbitrary JSON string data, represented as UTF-8
这里描述有点不对，应该是任意的 object（json 的对象），比如其他的我们是不支持的，比如 array 这种

2023-12-14 07:36 UTC, fahchen commented on lib/jet_ext/absinthe/types/scalar/object_json.ex
> +    end
```suggestion
    if Code.ensure_loaded?(Decimal) do
      require Decimal
  
      defp iterate(value) when Decimal.is_decimal(value) do
        if Decimal.integer?(value) do
          Decimal.to_integer(value)
        else
          Decimal.to_float(value)
        end
      end
    end
```

2023-12-14 07:36 UTC, fahchen commented on lib/jet_ext/absinthe/types/scalar/object_json.ex
> +    defp encode(value) do
这里只接受 map 比较好

2023-12-14 09:16 UTC, vanppo commented on lib/jet_ext/absinthe/types/scalar/object_json.ex
> +if Code.ensure_loaded?(Absinthe) && Code.ensure_loaded?(Jason) do
我看了下 jason 不是 optional 的 这里的 ensure 应该是多余的

2023-12-14 09:16 UTC, vanppo commented on lib/jet_ext/absinthe/types/scalar/object_json.ex
> +      raise Absinthe.SerializationError
错误的原因可以提示是因为输入不是 map 么

2023-12-14 10:16 UTC, c01dcat commented on lib/jet_ext/absinthe/types/scalar/object_json.ex
> +      raise Absinthe.SerializationError
https://github.com/absinthe-graphql/absinthe/blob/main/lib/absinthe/phase/document/result.ex#L54-L67，Absinthe 会捕获这类错误

2023-12-15 06:41 UTC, c01dcat commented on lib/jet_ext/absinthe/types/scalar/object_json.ex
> +if Code.ensure_loaded?(Absinthe) do
jet-ext 中 jason 不是 optional 的

2023-12-15 06:45 UTC, CptBreeza commented on lib/jet_ext/absinthe/types/scalar/object_json.ex
> +    defp encode(value) when is_map(value) do
这样不行，`is_map` 用在一个 struct 上时也会返回 true，得确认它是一个 map 并且不是一个 struct

2023-12-15 06:46 UTC, vanppo approved these changes

2023-12-15 06:47 UTC, CptBreeza commented on lib/jet_ext/absinthe/types/scalar/object_json.ex
> +      raise Absinthe.SerializationError
这里还是不要直接 raise 了，我看它是支持返回一个 :error tuple 的，你看一下
https://github.com/absinthe-graphql/absinthe/pull/1187

2023-12-15 07:14 UTC, fahchen commented on lib/jet_ext/absinthe/types/scalar/object_json.ex
测试用例加一下吧

2023-12-15 07:14 UTC, fahchen commented on lib/jet_ext/absinthe/types/scalar/object_json.ex
> +    defp encode(value) when is_map(value) do
我们这里是不是只处理基础的类型，遇到 struct 等不支持的类型就直接抛出异常，包括 map 内部可能会存在的不支持类型的值都这样处理？

2023-12-19 05:31 UTC, fahchen commented on lib/jet_ext/absinthe/types/scalar/object_json.ex
> +    raise Absinthe.SerializationError
是不是应该返回 error 啊？
```suggestion
    :error
```

2023-12-19 05:40 UTC, CptBreeza commented on lib/jet_ext/absinthe/types/scalar/object_json.ex
> +    raise Absinthe.SerializationError
serialize 是不能返回 :error 的

2023-12-19 06:10 UTC, fahchen approved these changes

2023-12-19 06:12 UTC, vanppo commented on lib/jet_ext/absinthe/types/scalar/object_json.ex
> +defmodule JetExt.Absinthe.Types.Scalar.ObjectJSON do
ensure absinthe

2023-12-19 06:12 UTC, vanppo commented on lib/jet_ext/absinthe/types/scalar/object_json.ex
> +  end
我记得上周结论应该是可以为 struct 吧

2023-12-19 06:40 UTC, CptBreeza commented on lib/jet_ext/absinthe/types/scalar/object_json.ex
> +  end
暂时没必要了，现在只用在 schemaless 那个 object 上面

2023-12-21 05:12 UTC, merged